apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecko
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecko
  template:
    metadata:
      labels:
        app: ecko
    spec:
      containers:
        - name: ecko
          image: junchaw/ecko:latest
          ports:
            - containerPort: 80
          env:
            - name: ECKO_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: ecko
  namespace: default
spec:
  selector:
    app: ecko
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecko
  namespace: default
spec:
  rules:
    - host: ecko.junchaw.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ecko
                port:
                  number: 80
